import { useState } from 'react';
import { BriefcaseBusiness, CalendarRange, Search, X } from 'lucide-react';
import { useGetEmployeeBalance, useGetEmployees, type Employee } from '@workspace/api-client-react';
import { PageHeader } from '@/components/layout';
import { Avatar, EmptyState, LoadingRows, QueryError } from '@/components/ui-pieces';
import { formatDays, formatShortDate } from '@/lib/leave';

export default function EmployeesPage() {
  const [search, setSearch] = useState('');
  const [selected, setSelected] = useState<Employee | null>(null);
  const query = useGetEmployees(search ? { search } : undefined);
  return <div><PageHeader eyebrow="구성원 · 연차 잔여" title="구성원" description="팀별 연차 사용 현황과 잔여 일수를 관리하세요." action={<div className="flex items-center gap-2 rounded-lg bg-[hsl(var(--muted))] px-3 py-2 text-[11px] font-semibold"><BriefcaseBusiness size={14} className="text-[hsl(var(--primary))]" />{query.data?.length || 0}명 재직 중</div>} /><div className="mx-auto max-w-[1440px] px-5 py-7 sm:px-8 md:px-10 md:py-9"><div className="mb-5 flex items-center justify-between"><div className="relative w-full max-w-[320px]"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-[hsl(var(--muted-foreground))]" /><input type="search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="이름, 부서, 직무 검색" data-testid="input-search-employees" className="h-10 w-full rounded-lg border border-[hsl(var(--input))] bg-[hsl(var(--card))] pl-9 pr-3 text-[12px] outline-none transition focus:border-[hsl(var(--ring))] focus:ring-2 focus:ring-[hsl(var(--ring)/.12)]" /></div><div className="hidden text-[11px] text-[hsl(var(--muted-foreground))] sm:block">행을 선택하면 상세 잔여 내역을 볼 수 있어요</div></div><div className="surface overflow-hidden"><div className="hidden grid-cols-[1.2fr_1fr_1fr_1fr_1fr] border-b border-[hsl(var(--border))] bg-[hsl(var(--muted)/.45)] px-5 py-3 text-[10px] font-bold text-[hsl(var(--muted-foreground))] md:grid"><span>구성원</span><span>입사일</span><span>부여</span><span>사용 / 대기</span><span>남은 연차</span></div>{query.isLoading && <div className="p-4"><LoadingRows count={5} /></div>}{query.isError && <div className="p-5"><QueryError onRetry={() => query.refetch()} /></div>}{!query.isLoading && !query.isError && !query.data?.length && <div className="p-5"><EmptyState title="검색 결과가 없어요" description="다른 이름이나 부서로 검색해 보세요." /></div>}{query.data?.map((employee, index) => <EmployeeRow employee={employee} key={employee.id} index={index} onOpen={() => setSelected(employee)} />)}</div></div>{selected && <EmployeeDrawer employee={selected} onClose={() => setSelected(null)} />}</div>;
}

function EmployeeRow({ employee, index, onOpen }: { employee: Employee; index: number; onOpen: () => void }) {
  const progress = employee.annualAllowance ? Math.min((employee.usedDays / employee.annualAllowance) * 100, 100) : 0;
  const colors = ['teal', 'peach', 'gold', 'sage'] as const;
  return <button type="button" onClick={onOpen} data-testid={`row-employee-${employee.id}`} className="grid w-full grid-cols-1 gap-3 border-b border-[hsl(var(--border))] px-4 py-4 text-left transition-colors last:border-0 hover:bg-[hsl(var(--muted)/.35)] md:grid-cols-[1.2fr_1fr_1fr_1fr_1fr] md:items-center md:px-5 md:py-4"><div className="flex items-center gap-3"><Avatar name={employee.name} color={colors[index % colors.length]} /><div><div className="text-[12px] font-bold">{employee.name}</div><div className="mt-1 text-[10px] text-[hsl(var(--muted-foreground))]">{employee.department} · {employee.role}</div></div></div><div className="pl-12 text-[11px] text-[hsl(var(--muted-foreground))] md:pl-0">{formatShortDate(employee.joinedAt)}</div><div className="flex items-center justify-between pl-12 md:block md:pl-0"><span className="text-[10px] text-[hsl(var(--muted-foreground))] md:hidden">연간 부여</span><span className="font-mono text-[13px]">{formatDays(employee.annualAllowance)}</span></div><div className="flex items-center gap-2 pl-12 md:block md:pl-0"><div className="flex justify-between text-[11px] md:block"><span>{formatDays(employee.usedDays)} 사용</span><span className="ml-2 text-[hsl(var(--muted-foreground))]">{formatDays(employee.pendingDays)} 대기</span></div><div className="mt-2 h-1.5 max-w-[120px] overflow-hidden rounded-full bg-[hsl(var(--muted))]"><div className="h-full rounded-full bg-[hsl(var(--primary))]" style={{ width: `${progress}%` }} /></div></div><div className="flex items-center justify-between pl-12 md:block md:pl-0"><span className="text-[10px] text-[hsl(var(--muted-foreground))] md:hidden">잔여 연차</span><span className="font-mono text-[15px] font-medium text-[hsl(var(--primary))]">{formatDays(employee.remainingDays)}</span></div></button>;
}

function EmployeeDrawer({ employee, onClose }: { employee: Employee; onClose: () => void }) {
  const query = useGetEmployeeBalance(employee.id);
  const balance = query.data;
  return <div className="fixed inset-0 z-50 flex justify-end bg-[hsl(var(--foreground)/.32)]" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside className="h-full w-full max-w-[420px] overflow-y-auto bg-[hsl(var(--card))] p-6 shadow-2xl sm:p-8" data-testid="employee-detail-drawer"><div className="mb-8 flex items-center justify-between"><div><div className="eyebrow mb-2">구성원 정보</div><h2 className="text-xl font-extrabold tracking-[-.05em]">{employee.name}</h2></div><button type="button" onClick={onClose} data-testid="button-close-employee-drawer" className="rounded-lg p-2 hover:bg-[hsl(var(--muted))]"><X size={19} /></button></div><div className="mb-6 flex items-center gap-3 rounded-xl bg-[hsl(var(--muted)/.6)] p-4"><Avatar name={employee.name} color="teal" /><div><div className="text-sm font-bold">{employee.department}</div><div className="mt-1 text-[11px] text-[hsl(var(--muted-foreground))]">{employee.role} · {formatShortDate(employee.joinedAt)} 입사</div></div></div>{query.isLoading && <LoadingRows count={2} />}{query.isError && <QueryError onRetry={() => query.refetch()} />}{balance && <div className="animate-rise"><div className="mb-3 flex items-center gap-2 text-xs font-bold"><CalendarRange size={15} className="text-[hsl(var(--primary))]" />올해 연차 잔여 내역</div><div className="grid grid-cols-3 gap-2"><BalanceCard label="부여" value={balance.annualAllowance} /><BalanceCard label="사용" value={balance.usedDays} tone="peach" /><BalanceCard label="남음" value={balance.remainingDays} tone="teal" /></div><div className="mt-4 rounded-xl border border-[hsl(var(--border))] p-4"><div className="mb-3 flex justify-between text-[11px]"><span className="text-[hsl(var(--muted-foreground))]">사용률</span><span className="font-mono">{balance.annualAllowance ? Math.round((balance.usedDays / balance.annualAllowance) * 100) : 0}%</span></div><div className="h-2 overflow-hidden rounded-full bg-[hsl(var(--muted))]"><div className="h-full rounded-full bg-[hsl(var(--primary))]" style={{ width: `${balance.annualAllowance ? (balance.usedDays / balance.annualAllowance) * 100 : 0}%` }} /></div><div className="mt-3 text-[10px] text-[hsl(var(--muted-foreground))]">승인 대기 {formatDays(balance.pendingDays)} 포함 시 잔여 {formatDays(balance.remainingDays)}</div></div></div>}</aside></div>;
}

function BalanceCard({ label, value, tone = 'gold' }: { label: string; value: number; tone?: 'gold' | 'peach' | 'teal' }) { const styles = { gold: 'bg-[hsl(var(--accent)/.2)] text-[hsl(var(--accent))]', peach: 'bg-[hsl(var(--destructive)/.15)] text-[hsl(var(--destructive))]', teal: 'bg-[hsl(var(--primary)/.1)] text-[hsl(var(--primary))]' }; return <div className={`rounded-xl p-3 ${styles[tone]}`}><div className="font-mono text-xl tracking-[-.07em] font-bold">{value}</div><div className="mt-1 text-[10px] opacity-70 font-semibold">{label}</div></div>; }